# Generated by Django 2.2.5 on 2019-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_profile_test_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
