# Generated by Django 2.2.5 on 2019-12-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20191201_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
