# Generated by Django 2.2.5 on 2019-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
    ]
