# Generated by Django 2.2.5 on 2019-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190916_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_des',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
