# Generated by Django 2.2.5 on 2019-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190918_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Enter tags separated by spaces. Do not enter more than 5 tags', max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Try to keep the title short, within 80 characters.', max_length=80, unique=True),
        ),
    ]
