# Generated by Django 2.2.5 on 2019-09-26 08:36

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190923_0523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(default='Description', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markupfield.fields.MarkupField(help_text='This field supports all markup formatting', rendered_field=True),
        ),
    ]
