# Generated by Django 2.2.5 on 2019-09-26 08:47

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190926_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_short_des_rendered',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='short_des_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_des',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text='This will be displayed on the home page.If you leave it blank, the first 50 words from your article will be displayed.It can not be more than 50 words', max_length=500, rendered_field=True),
        ),
    ]
