# Generated by Django 2.2.5 on 2019-09-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_short_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_des',
        ),
    ]
