# Generated by Django 2.2.5 on 2019-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_profile_bookmarked_posts'),
        ('post', '0018_unpublishedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnPublishedPost',
        ),
    ]
