# Generated by Django 2.2.5 on 2019-12-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20191205_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
