# Generated by Django 2.2.5 on 2019-12-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20191215_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', editable=False, upload_to=''),
        ),
    ]
