# Generated by Django 2.2.5 on 2019-12-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', editable=False, null=True, upload_to=''),
        ),
    ]
