# Generated by Django 2.2.5 on 2019-12-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20191215_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
