# Generated by Django 2.2.5 on 2019-12-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_auto_20191218_2210'),
        ('post', '0042_auto_20191226_0617'),
    ]

    operations = [
    ]
