# Generated by Django 2.2.5 on 2019-12-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0044_auto_20191228_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
