# Generated by Django 2.2.5 on 2020-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0048_auto_20200115_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Draft'), (0, 'Queued'), (1, 'Publish')], default=-1, max_length=1),
        ),
    ]
