# Generated by Django 3.0.8 on 2020-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0056_auto_20200208_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_change',
            field=models.BooleanField(default=False, verbose_name='Change Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Do not forget to change this before publishing.', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, 'Draft'), (0, 'Queue'), (1, 'Publish')], default=-1),
        ),
    ]
