# Generated by Django 3.0.8 on 2021-01-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0057_auto_20200804_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.FloatField(default=0.0),
        ),
    ]
