# Generated by Django 3.1.9 on 2021-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0059_auto_20210114_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blog'),
        ),
    ]
