# Generated by Django 2.2.5 on 2019-09-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190909_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
