# Generated by Django 2.2.5 on 2019-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20190916_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_des',
            field=models.CharField(default='', max_length=300),
        ),
    ]
