# Generated by Django 2.2.5 on 2019-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20190916_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_des',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
