# Generated by Django 2.2.5 on 2019-12-05 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_post_date_published'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='post',
    #         name='date_published',
    #         field=models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now()), null=True),
    #     ),
    # ]
