# Generated by Django 2.2.5 on 2019-12-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_auto_20191206_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
