# Generated by Django 2.2.5 on 2019-12-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0034_auto_20191215_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Do not forget to change this before publishing', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', editable=False, null=True, upload_to=''),
        ),
    ]
