# Generated by Django 2.2.5 on 2019-12-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0041_remove_post_hits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
