# Generated by Django 2.2.5 on 2019-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0042_auto_20191226_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
    ]
