# Generated by Django 2.2.5 on 2020-01-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0044_auto_20191228_1830'),
        ('Blog', '0045_auto_20191231_0732'),
    ]

    operations = [
    ]
