# Generated by Django 2.2.5 on 2020-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0047_auto_20200109_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[(-1, 'Draft'), (0, 'Queued'), (1, 'Publish')], default=-1, max_length=30),
        ),
    ]
