# Generated by Django 2.2.5 on 2020-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0050_auto_20200115_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Draft'), (0, 'Queued'), (1, 'Published')], default=-1),
        ),
    ]
