# Generated by Django 2.2.5 on 2019-09-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
