# Generated by Django 2.2.5 on 2019-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20190913_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
