# Generated by Django 2.2.5 on 2019-09-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190918_2030'),
        ('user_profile', '0014_profile_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked_posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
