# Generated by Django 2.2.5 on 2019-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_profile_bookmarked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_cols',
            field=models.BooleanField(default=True),
        ),
    ]
