# Generated by Django 2.2.5 on 2019-12-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_auto_20191201_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
    ]
